// Shared (client + server) media model: amp entities and sources, the radio station catalog,
// snapshot / list / queue shapes, the action union and demo data. Contains no secrets.
import catalog from "@/data/radio-stations.json";
import type { Lang } from "./i18n";

// ---- Amp (Yamaha R-N500) ----
export const AMP_SOURCES = ["SERVER", "CD", "PHONO", "TUNER", "NET RADIO"] as const;
export type AmpSource = (typeof AMP_SOURCES)[number];
export const isAmpSource = (v: unknown): v is AmpSource =>
  typeof v === "string" && (AMP_SOURCES as readonly string[]).includes(v);

const MEDIA_PLUG = "smart_switch_23081678814571510d0548e1e9d69992";
export const AMP = {
  player: "media_player.r_n500_main",
  volumeDb: "number.r_n500_main_volume_db",
  dlna: "media_player.yamaha_r_n500",
  plug: `switch.${MEDIA_PLUG}_outlet`,
  plugPower: `sensor.${MEDIA_PLUG}_power`,
  tv: "media_player.bravia_xr_65x90k",
  movieActive: "input_boolean.movie_mode_active",
  movieOn: "script.movie_mode",
  movieOff: "script.movie_mode_off",
  /** HA config entry of the yamaha_ynca integration; reloading it reconnects right after power-on. */
  yncaEntryId: "01M0ZMQXMTWAAW7BXTBCXD1YZR",
  volumeMinDb: -80.5,
  volumeMaxDb: 16.5,
  /** One 5-way press. */
  volumeStepDb: 2,
} as const;

// ---- Radio catalog (src/data/radio-stations.json, generated by scripts/radio-stations.py) ----
export type RadioStation = {
  id: string;
  name: string;
  url: string;
  codec: string;
  bitrate: number;
  /** Real FM frequency in MHz for the local list, null elsewhere. */
  fm: number | null;
  logo: string | null;
};
export type RadioList = {
  id: string;
  /** Category name inside YTuner "My Stations" (menu order = catalog order). */
  ytunerCategory: string;
  stations: RadioStation[];
};

const cleanLogo = (logo: unknown): string | null =>
  typeof logo === "string" && /^https?:\/\//.test(logo) ? logo : null;

export const RADIO_LISTS: RadioList[] = (catalog as { lists: RadioList[] }).lists.map((l) => ({
  id: l.id,
  ytunerCategory: l.ytunerCategory,
  stations: l.stations.map((s) => ({
    id: s.id,
    name: s.name,
    url: s.url,
    codec: s.codec,
    bitrate: s.bitrate,
    fm: typeof s.fm === "number" ? s.fm : null,
    logo: cleanLogo(s.logo),
  })),
}));
/** The YTuner bookmark list, shown as the "favourites" band. */
export const FAVOURITES_LIST_ID = "favourites";
export const RADIO_LIST_IDS = [FAVOURITES_LIST_ID, ...RADIO_LISTS.map((l) => l.id)] as [
  string,
  ...string[],
];
export const RADIO_STATION_IDS = RADIO_LISTS.flatMap((l) => l.stations.map((s) => s.id)) as [
  string,
  ...string[],
];
export const findStation = (id: string): RadioStation | undefined =>
  RADIO_LISTS.flatMap((l) => l.stations).find((s) => s.id === id);
/** Hosts the image route may fetch logos from (besides the configured servers). */
export const CATALOG_LOGO_HOSTS = Array.from(
  new Set(
    RADIO_LISTS.flatMap((l) => l.stations)
      .map((s) => s.logo)
      .filter((u): u is string => u !== null)
      .map((u) => new URL(u).hostname),
  ),
);

export type RadioStationView = RadioStation & {
  /** YTuner StationId (MS_…) when YTuner knows the stream URL, else null. */
  ytunerId: string | null;
  favourite: boolean;
};
export type RadioListView = { id: string; stations: RadioStationView[] };
/** Where the amp's NET RADIO cursor was left by us (list id + 0-based station index). */
export type RadioPosition = { list: string; index: number };
export type RadioListsResult = {
  configured: boolean;
  error?: string;
  lists: RadioListView[];
  current: RadioPosition | null;
};

// ---- Now playing / snapshot ----
export type AmpStatus = {
  /** HA knows the entity (not unavailable). */
  available: boolean;
  on: boolean;
  /** HA state: off, on, idle, playing, paused, unavailable. */
  state: string;
  source: AmpSource | null;
  volumeDb: number | null;
  /** 0..1 */
  volume: number | null;
  muted: boolean;
};
export type NowPlayingKind = "radio" | "music" | "fm" | "tv" | "phono" | "none";
export type NowPlaying = {
  kind: NowPlayingKind;
  title: string | null;
  artist: string | null;
  album: string | null;
  /** NET RADIO station or FM channel text. */
  station: string | null;
  /** Jellyfin item id to fetch art for via /media/img?item=… */
  artItemId: string | null;
  /** Catalog station id when the playing station is one of ours. */
  stationId: string | null;
  preset: number | null;
};
export type PowerOnStep = "plug" | "wait" | "reload" | "turn_on" | "source" | "done" | "failed";
export type PowerOnStatus = {
  running: boolean;
  step: PowerOnStep;
  startedAt: number;
  updatedAt: number;
  elapsedMs: number;
  source: AmpSource | null;
  error?: string;
};
export type MediaSnapshot = {
  amp: AmpStatus;
  nowPlaying: NowPlaying;
  tv: { state: string; source: string | null };
  plugOn: boolean;
  movieActive: boolean;
  queue: QueueProgress | null;
  radio: RadioPosition | null;
  powerOn: PowerOnStatus | null;
};
export type MediaSnapshotResult = {
  /** HA token present. */
  configured: boolean;
  /** AMP_HOST present (XML / UPnP features). */
  amp: boolean;
  /** Jellyfin url + key present. */
  jellyfin: boolean;
  error?: string;
  snapshot: MediaSnapshot | null;
  lang: Lang;
};

// ---- Jellyfin ----
export type MusicTrack = {
  id: string;
  title: string;
  artist: string | null;
  album: string | null;
  albumId: string | null;
  durationMs: number;
  /** Jellyfin container: mp3, flac, ogg, opus, asf, … */
  container: string | null;
  artItemId: string | null;
};
export type MusicItemKind = "album" | "artist" | "track" | "mix";
export type MusicListItem = {
  kind: MusicItemKind;
  id: string;
  title: string;
  detail: string;
  artItemId: string | null;
  /** Album rows on the artist screen: year, release date (yyyy-mm-dd, often just "yyyy-01-01" when
   *  the tags only knew the year), number of tracks and the first genre, when known. */
  year?: number | null;
  releaseDate?: string | null;
  trackCount?: number | null;
  genre?: string | null;
};
export const MUSIC_TABS = ["mixes", "suggested", "artists", "albums", "recent"] as const;
export type MusicTab = (typeof MUSIC_TABS)[number];
export const MUSIC_PAGE_SIZE = 8;
export type MusicListResult = {
  configured: boolean;
  error?: string;
  tab: MusicTab;
  page: number;
  pages: number;
  items: MusicListItem[];
};
export type PlaySelection = { kind: MusicItemKind; id: string };
/** Search screen (F4 on the music screen): artists and albums whose names start with the typed words.
 *  Results appear from the second character; the list holds one screen, no paging. */
export const SEARCH_MIN_CHARS = 2;
export const SEARCH_RESULT_ROWS = 5;
export const SEARCH_MAX_CHARS = 40;
export type MusicSearchResult = {
  configured: boolean;
  error?: string;
  query: string;
  items: MusicListItem[];
};
/** Artist screen (Enter on an artist in the lists or the search): their albums, oldest first. */
export type ArtistAlbumsResult = {
  configured: boolean;
  error?: string;
  artist: { id: string; title: string; artItemId: string | null };
  page: number;
  pages: number;
  total: number;
  items: MusicListItem[];
};
export const MIX_IDS = [
  "daily",
  "discover",
  "party",
  "dancing",
  "rock",
  "pop",
  "s60",
  "s70",
  "s80",
  "s90",
  "s2000",
  "relaxed",
  "evening",
  "jazz",
  "blues",
  "punk",
  "metal",
  "electronic",
  "classical",
] as const;
export type MixId = (typeof MIX_IDS)[number];

// ---- Playback queue (server-owned; the browser only ever sees QueueProgress) ----
export type QueueTrack = MusicTrack & { streamUrl: string };
export type QueueStatus = "playing" | "paused" | "stopped" | "ended";
export type QueueState = {
  id: string;
  title: string;
  tracks: QueueTrack[];
  index: number;
  status: QueueStatus;
  /** Wall clock (ms) when the current track started counting from offsetMs; null unless playing. */
  startedAt: number | null;
  /** Position inside the current track at startedAt (after a seek / resume). */
  offsetMs: number;
  /** SetNextAVTransportURI already sent for index + 1. */
  nextPushed: boolean;
};
/** The whole queue for the playlist screen (stream URLs stripped). */
export type QueueList = { title: string; index: number; status: QueueStatus; tracks: MusicTrack[] };
export type QueueProgress = {
  title: string;
  index: number;
  count: number;
  track: MusicTrack | null;
  positionMs: number;
  durationMs: number;
  status: QueueStatus;
};

// ---- Actions ----
export type MediaAction =
  | { type: "amp.power"; on: boolean }
  | { type: "amp.source"; source: AmpSource }
  | { type: "amp.volume.step"; delta: 1 | -1 }
  | { type: "amp.volume.db"; db: number }
  | { type: "amp.volume.set"; level: number }
  | { type: "amp.reload" }
  | { type: "plug"; on: boolean }
  | { type: "tv"; op: "turn_on" | "turn_off" | "toggle" | "volume_mute" }
  | { type: "movie"; on: boolean }
  | { type: "fm.preset"; preset: number }
  | { type: "fm.frequency"; mhz: number }
  | { type: "radio.step"; delta: 1 | -1 }
  | { type: "radio.favourite"; stationId: string; add: boolean }
  /** NET RADIO stream stop / play (Enter on the radio screen). */
  | { type: "radio.playback"; op: "play" | "stop" }
  | { type: "queue"; op: "next" | "prev" | "pause" | "resume" | "toggle" | "stop" }
  /** Playlist screen: play track `index` of the queue. */
  | { type: "queue.jump"; index: number }
  /** TV off, amp to standby, then (3 s later) the media plug off. */
  | { type: "all_off" };
export type MediaActionResult = { ok: boolean; error?: string; snapshot?: MediaSnapshot | null };

// ---- Demo data (no env) ----
export const demoTracks = (): MusicTrack[] =>
  [
    ["Where Is Love", "McCoy Tyner Trio", "Infinity", 332000],
    ["New Born", "Muse", "Origin of Symmetry", 365000],
    ["Come Sail Away", "Styx", "Greatest Hits", 364000],
    ["So What", "Miles Davis", "Kind of Blue", 562000],
  ].map(([title, artist, album, durationMs], i) => ({
    id: `demo-${i + 1}`,
    title: String(title),
    artist: String(artist),
    album: String(album),
    albumId: `demo-album-${i + 1}`,
    durationMs: Number(durationMs),
    container: "mp3",
    artItemId: null,
  }));

export function demoMediaSnapshot(): MediaSnapshot {
  const station = RADIO_LISTS[0]?.stations[0];
  return {
    amp: {
      available: true,
      on: true,
      state: "playing",
      source: "NET RADIO",
      volumeDb: -44.5,
      volume: 0.37,
      muted: false,
    },
    nowPlaying: {
      kind: "radio",
      title: "Zara Larsson - Memory Lane",
      artist: null,
      album: null,
      station: station?.name ?? "1LIVE",
      artItemId: null,
      stationId: station?.id ?? null,
      preset: null,
    },
    tv: { state: "off", source: null },
    plugOn: true,
    movieActive: false,
    queue: null,
    radio: station ? { list: RADIO_LISTS[0]?.id ?? "local", index: 0 } : null,
    powerOn: null,
  };
}

export function demoRadioLists(): RadioListsResult {
  return {
    configured: false,
    lists: [
      { id: FAVOURITES_LIST_ID, stations: [] },
      ...RADIO_LISTS.map((l) => ({
        id: l.id,
        stations: l.stations.map((s) => ({ ...s, ytunerId: null, favourite: false })),
      })),
    ],
    current: { list: RADIO_LISTS[0]?.id ?? "local", index: 0 },
  };
}

/** Demo mode: Enter on a list item "plays" the demo tracks from the first one, without a server. */
export function demoQueue(title: string): QueueProgress {
  const tracks = demoTracks();
  const track = tracks[0]!;
  return {
    title,
    index: 0,
    count: tracks.length,
    track,
    positionMs: 0,
    durationMs: track.durationMs,
    status: "playing",
  };
}

export function demoMusicList(tab: MusicTab, page: number): MusicListResult {
  const tracks = demoTracks();
  const items: MusicListItem[] =
    tab === "mixes"
      ? MIX_IDS.map((id) => ({ kind: "mix", id, title: id, detail: "20", artItemId: null }))
      : tab === "artists"
        ? tracks.map((t) => ({
            kind: "artist",
            id: `artist-${t.id}`,
            title: t.artist ?? "",
            detail: "3",
            artItemId: null,
          }))
        : tab === "suggested"
          ? tracks.map((t) => ({
              kind: "track",
              id: t.id,
              title: t.title,
              detail: t.artist ?? "",
              artItemId: null,
            }))
          : tracks.map((t) => ({
              kind: "album",
              id: t.albumId ?? t.id,
              title: t.album ?? "",
              detail: t.artist ?? "",
              artItemId: null,
            }));
  return { configured: false, tab, page: 0, pages: 1, items: page === 0 ? items : [] };
}

/** Demo artist screen: the demo albums of that demo artist (`artist-<track id>`). */
export function demoArtistAlbums(artistId: string, page: number): ArtistAlbumsResult {
  const tracks = demoTracks();
  const seed = tracks.find((t) => `artist-${t.id}` === artistId);
  const name = seed?.artist ?? "";
  const seen = new Set<string>();
  const items: MusicListItem[] = tracks
    .filter(
      (t) =>
        t.artist === name && t.album && !seen.has(t.albumId ?? t.id) && seen.add(t.albumId ?? t.id),
    )
    .map((t) => ({
      kind: "album",
      id: t.albumId ?? t.id,
      title: t.album ?? "",
      detail: "",
      artItemId: null,
      year: 1999,
      releaseDate: "1999-04-17",
      trackCount: 4,
      genre: "Jazz",
    }));
  return {
    configured: false,
    artist: { id: artistId, title: name, artItemId: null },
    page: 0,
    pages: 1,
    total: items.length,
    items: page === 0 ? items : [],
  };
}

/** Demo search: the demo artists and albums whose name contains the query (artists first). */
export function demoMusicSearch(query: string): MusicSearchResult {
  const q = query.trim().toLowerCase();
  const seen = new Set<string>();
  const items = [...demoMusicList("artists", 0).items, ...demoMusicList("albums", 0).items].filter(
    (item) => {
      if (!q || seen.has(item.id) || !item.title.toLowerCase().includes(q)) return false;
      seen.add(item.id);
      return true;
    },
  );
  return { configured: false, query, items: items.slice(0, SEARCH_RESULT_ROWS) };
}
